name       : libxt
version    : 1.1.5
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXt-1.1.5.tar.gz : b59bee38a9935565fa49dc1bfe84cb30173e2e07e1dcdf801430d4b54eb0caa3
license    :
    - MIT
summary    : X Toolkit Intrinsics library
component  : xorg.library
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(ice)
    - pkgconfig32(ice)
    - pkgconfig(sm)
    - pkgconfig32(sm)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - devel :
        - /usr/share/man
description: |
    libXt provides the X Toolkit Intrinsics, an abstract widget library upon which other toolkits are based.  Xt is the basis for many toolkits, including the Athena widgets (Xaw), and LessTif (a Motif implementation).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
