name       : libxt
version    : 1.1.5
release    : 9
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXt-1.1.5.tar.gz : b59bee38a9935565fa49dc1bfe84cb30173e2e07e1dcdf801430d4b54eb0caa3
license    : MIT
component  : xorg.library
summary    : X Toolkit Intrinsics library
description: |
    libXt provides the X Toolkit Intrinsics, an abstract widget library upon which other toolkits are based.  Xt is the basis for many toolkits, including the Athena widgets (Xaw), and LessTif (a Motif implementation).
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(ice)
    - pkgconfig32(sm)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
