name       : libxt
version    : 1.2.1
release    : 13
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXt-1.2.1.tar.gz : 6da1bfa9dd0ed87430a5ce95b129485086394df308998ebe34d98e378e3dfb33
license    : MIT
component  : xorg.library
summary    : X Toolkit Intrinsics library
description: |
    libXt provides the X Toolkit Intrinsics, an abstract widget library upon which other toolkits are based.  Xt is the basis for many toolkits, including the Athena widgets (Xaw), and LessTif (a Motif implementation).
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(ice)
    - pkgconfig32(sm)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
